package br.com.model.enums;

public enum CategoriaLivros {
    DIREITO_CIVIL,
    DIREITO_PENAL,
    DIREITO_CONSTITUCIONAL,
    DIREITO_ADMINISTRATIVO,
    DIREITO_TRABALHISTA,
    DIREITO_EMPRESARIAL,
    DIREITO_TRIBUTARIO,
    DIREITO_PROCESSUAL_CIVIL,
    DIREITO_PROCESSUAL_PENAL,
    DIREITO_AMBIENTAL,
    DIREITO_INTERNACIONAL,
    DIREITO_PREVIDENCIARIO,
    DIREITO_DIGITAL,
    DIREITO_DO_CONSUMIDOR,
    DIREITO_IMOBILIARIO,
    DIREITO_BANCARIO,
    DIREITO_FAMILIA,
    DIREITO_SUCESSOES,
    DIREITO_PENAL_ECONOMICO,
    DIREITO_ARBITRAGEM;
}
